package Projects;

public class Problem2 {

	/*Each new term in the Fibonacci sequence is generated by adding the previous 
	 * two terms. By starting with 1 and 2, the first 10 terms will be:
	 
			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed 
	four million, find the sum of the even-valued terms.
	 */
	
	public static void main(String args[]) {
	
		int evenSum = 2;
		
		int fib = 2;
		int prevFib = 1;
		int tempFib = 0;
		
		while(fib < 4000000) {
			tempFib = fib;
			fib += prevFib;
			prevFib = tempFib;
			
			if(fib%2==0)	evenSum += fib;
		}
		
		System.out.print(evenSum);
		
	}
}
